---
title: "Publications"
page-layout: full
title-block-banner: true
format:
  html:
    css: assets/index.css
---

::: {.main style="width:60%; float: left;"}
<i> If you have trouble accessing any of these, please [email me](mailto:matthew.woodstock@morgan.edu).</i>

## 2024
* <b>Woodstock, M.S.</b>, A. T. Bevans, M. Sulyman, J. Maples, S. Knoche, T. F. Ihde. (2024) The economic impacts of living habitat changes in the Virginia Middle Peninsula, Chesapeake Bay. Ecological Modelling.

* Martin A. P., A. B. Dominguez, C. A. Baker, C. M. J. Baumas, K. M. Bisson, E. Cavan, M. Freilich, E. Galbraith, M. Gali, S. Hensen, K. F. Kvale, C. Lemmen, L. Y. Luo, H. McMonagle, F. deM. Virissimo, K. O. Moller, C. Richon, I. Suresh, J. D. Wison, <b>M. S. Woodstock</b>, A. Yool. (2024) When to add a new process to a model, and when not: A marine biogeochemical perspective. Ecological Modelling. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1016/j.ecolmodel.2024.110870)

## 2023
* **Woodstock, M.S.**, J.J. Kiszka, M. Rafael Ramírez-León, T.T. Sutton, K. Fennel, B. Wang, Y. Zhang (2024) Cetacean-mediated vertical nitrogen transport in the oceanic realm. Limnology and Oceanography. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1002/lno.12093)

* Richards, T.M., T.T. Sutton., **M.S. Woodstock**, H. Judkins, D. Wells. (2023). Body size, depth of occurrence, and local oceanography shape trophic structure in a diverse deep-pelagic micronekton assemblage. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1016/j.pocean.2023.102998)

## 2022

* **Woodstock, M.S.** (2022). Ecological modeling in the oceanic zone: A Gulf of Mexico case study. Doctoral Dissertation. Florida International University. **Email for pdf**

* **Woodstock, M.S.**, Y. Zhang. (2022). Towards ecosystem modeling in the deep sea: A review of past efforts and primer for the future. Deep-Sea Research Part I: Oceanographic Research Papers. 188:103851 [<i class="fa-solid fa-link"></i>](https://doi.org/10.1016/j.dsr.2022.103851)

* **Woodstock, M.S.**, T.T. Sutton, Y. Zhang. (2022). A trait-based carbon export model for mesopelagic fishes in the Gulf of Mexico with consideration of asynchronous vertical migration, flux boundaries, and feeding guilds. Limnology and Oceanography. 67:1443–1455. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1002/lno.12093)

* Kiszka, J.J., **M.S., Woodstock**, M. Heithaus. (2022). Functional roles and ecological importance of small cetaceans in aquatic ecosystems. Frontiers in Marine Science. [<i class="fa-solid fa-link"></i>](https://doi.org/10.3389/fmars.2022.803173)


## 2021

* **Woodstock, M.S.**, T.T. Sutton, T. Frank, Y. Zhang. (2021). An early warning sign: trophic structure changes in the oceanic Gulf of Mexico from 2011–2018. Ecological Modelling. 445:109509. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1016/j.ecolmodel.2021.109509)


## 2020

* **Woodstock, M.S.**, C.A. Blanar, T.T. Sutton. (2020). Diet and parasites of a mesopelagic fish assemblage in the Gulf of Mexico. Marine Biology. 167:184  [<i class="fa-solid fa-link"></i>](https://doi.org/10.1007/s00227-020-03796-6)

## 2019


* Beck, H.N., A. Cohen, T. McKenzie, R. Weisend, K.W. Wikins, **M.S. Woodstock**. (2019). Broadening Horizons: Graduate Students Participating in International Collaborations Through the Limnology and Oceanography Research Exchange (LOREX) Program. Limnology and Oceanography Bulletin. 28:85–89. [<i class="fa-solid fa-link"></i>](https://doi.org/10.1002/lob.10339) 

* **Woodstock, M.S.**, C. Golightly, D. Fenolio, J.A. Moore. (2019). <i>Larsonia pterophylla</i> (Cnidaria, Pandeidae) parasitic on two Anguilliformes: <i>Paraconger</i> sp. (Congridae) and <i>Callenchelyini</i> sp. (Ophichthidae) in the Gulf of Mexico. Gulf and Caribbean Research. 30:SC7–10. [<i class="fa-solid fa-link"></i>](https://doi.org/10.18785/gcr.3001.05)


## 2018

* **Woodstock, M.S.**. (2018). Trophic Ecology and Parasitism of a Mesopelagic Fish Assemblage. Nova Southeastern University. Master's Thesis. [<i class="fa-solid fa-link"></i>](https://nsuworks.nova.edu/occ_stuetd/469/)

:::
